Button in cloze
iqb-berlin/verona-modules-aspect pull request #353
Opened 2022-10-13 14:28 UTC by rhenck

2022-10-13 15:07 UTC, jojohoch requested changes
Cannot reload navigation buttons of cloze elements in editor

2022-10-13 16:21 UTC, rhenck commented
Hm kann ich nicht reproduzieren. Müssen wir morgen mal gemeinsam untersuchen.

2022-10-14 08:02 UTC, jojohoch approved these changes

2022-10-14 08:10 UTC, jojohoch commented on projects/common/components/compound-elements/cloze/cloze.component.ts
> +        <span *ngIf="['ToggleButton', 'DropList', 'TextField', 'Button'].includes(subPart.type)">
Funktionsaufruf (.includes) im Binding, sollte eigentlich unterlassen werden

2022-10-14 08:12 UTC, jojohoch commented on projects/common/models/elements/compound-elements/cloze/cloze.ts
> +      if (['ToggleButton', 'DropList', 'TextField', 'Button'].includes(subNode.type) &&
wieder Binding mit Funktionsaufruf

2022-10-14 08:12 UTC, jojohoch commented on projects/common/models/elements/compound-elements/cloze/cloze.ts
> +              ['TextField', 'DropList', 'ToggleButton', 'Button'].includes(paraPart.type) ?
Binding mit Funktionsaufruf

2022-10-18 13:38 UTC, jojohoch requested changes

2022-10-20 13:31 UTC, jojohoch approved these changes

2022-10-20 13:35 UTC, jojohoch reviewed
Kann in Master gemerged werden

2022-10-25 17:37 UTC, merged